// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: tinyurl.proto

package api_tinyurl

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TinyURLEncode
type TinyURLEncodeResObj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turl          string                 `protobuf:"bytes,1,opt,name=turl,proto3" json:"turl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TinyURLEncodeResObj) Reset() {
	*x = TinyURLEncodeResObj{}
	mi := &file_tinyurl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TinyURLEncodeResObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinyURLEncodeResObj) ProtoMessage() {}

func (x *TinyURLEncodeResObj) ProtoReflect() protoreflect.Message {
	mi := &file_tinyurl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinyURLEncodeResObj.ProtoReflect.Descriptor instead.
func (*TinyURLEncodeResObj) Descriptor() ([]byte, []int) {
	return file_tinyurl_proto_rawDescGZIP(), []int{0}
}

func (x *TinyURLEncodeResObj) GetTurl() string {
	if x != nil {
		return x.Turl
	}
	return ""
}

type TinyURLEncodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TinyURLEncodeReq) Reset() {
	*x = TinyURLEncodeReq{}
	mi := &file_tinyurl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TinyURLEncodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinyURLEncodeReq) ProtoMessage() {}

func (x *TinyURLEncodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_tinyurl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinyURLEncodeReq.ProtoReflect.Descriptor instead.
func (*TinyURLEncodeReq) Descriptor() ([]byte, []int) {
	return file_tinyurl_proto_rawDescGZIP(), []int{1}
}

func (x *TinyURLEncodeReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type TinyURLEncodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *TinyURLEncodeResObj   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TinyURLEncodeResp) Reset() {
	*x = TinyURLEncodeResp{}
	mi := &file_tinyurl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TinyURLEncodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinyURLEncodeResp) ProtoMessage() {}

func (x *TinyURLEncodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_tinyurl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinyURLEncodeResp.ProtoReflect.Descriptor instead.
func (*TinyURLEncodeResp) Descriptor() ([]byte, []int) {
	return file_tinyurl_proto_rawDescGZIP(), []int{2}
}

func (x *TinyURLEncodeResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TinyURLEncodeResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TinyURLEncodeResp) GetData() *TinyURLEncodeResObj {
	if x != nil {
		return x.Data
	}
	return nil
}

// TinyURLDecode
type TinyURLDecodeResObj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TinyURLDecodeResObj) Reset() {
	*x = TinyURLDecodeResObj{}
	mi := &file_tinyurl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TinyURLDecodeResObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinyURLDecodeResObj) ProtoMessage() {}

func (x *TinyURLDecodeResObj) ProtoReflect() protoreflect.Message {
	mi := &file_tinyurl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinyURLDecodeResObj.ProtoReflect.Descriptor instead.
func (*TinyURLDecodeResObj) Descriptor() ([]byte, []int) {
	return file_tinyurl_proto_rawDescGZIP(), []int{3}
}

func (x *TinyURLDecodeResObj) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type TinyURLDecodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turl          string                 `protobuf:"bytes,1,opt,name=turl,proto3" json:"turl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TinyURLDecodeReq) Reset() {
	*x = TinyURLDecodeReq{}
	mi := &file_tinyurl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TinyURLDecodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinyURLDecodeReq) ProtoMessage() {}

func (x *TinyURLDecodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_tinyurl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinyURLDecodeReq.ProtoReflect.Descriptor instead.
func (*TinyURLDecodeReq) Descriptor() ([]byte, []int) {
	return file_tinyurl_proto_rawDescGZIP(), []int{4}
}

func (x *TinyURLDecodeReq) GetTurl() string {
	if x != nil {
		return x.Turl
	}
	return ""
}

type TinyURLDecodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *TinyURLDecodeResObj   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TinyURLDecodeResp) Reset() {
	*x = TinyURLDecodeResp{}
	mi := &file_tinyurl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TinyURLDecodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinyURLDecodeResp) ProtoMessage() {}

func (x *TinyURLDecodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_tinyurl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinyURLDecodeResp.ProtoReflect.Descriptor instead.
func (*TinyURLDecodeResp) Descriptor() ([]byte, []int) {
	return file_tinyurl_proto_rawDescGZIP(), []int{5}
}

func (x *TinyURLDecodeResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TinyURLDecodeResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TinyURLDecodeResp) GetData() *TinyURLDecodeResObj {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_tinyurl_proto protoreflect.FileDescriptor

const file_tinyurl_proto_rawDesc = "" +
	"\n" +
	"\rtinyurl.proto\x1a\x1cgoogle/api/annotations.proto\")\n" +
	"\x13TinyURLEncodeResObj\x12\x12\n" +
	"\x04turl\x18\x01 \x01(\tR\x04turl\"$\n" +
	"\x10TinyURLEncodeReq\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"c\n" +
	"\x11TinyURLEncodeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.TinyURLEncodeResObjR\x04data\"'\n" +
	"\x13TinyURLDecodeResObj\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"&\n" +
	"\x10TinyURLDecodeReq\x12\x12\n" +
	"\x04turl\x18\x01 \x01(\tR\x04turl\"c\n" +
	"\x11TinyURLDecodeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.TinyURLDecodeResObjR\x04data2\xb1\x01\n" +
	"\aTinyURL\x12R\n" +
	"\rTinyURLEncode\x12\x11.TinyURLEncodeReq\x1a\x12.TinyURLEncodeResp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/tinyurl/encode\x12R\n" +
	"\rTinyURLDecode\x12\x11.TinyURLDecodeReq\x1a\x12.TinyURLDecodeResp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/tinyurl/decodeB\x0fZ\r.;api_tinyurlb\x06proto3"

var (
	file_tinyurl_proto_rawDescOnce sync.Once
	file_tinyurl_proto_rawDescData []byte
)

func file_tinyurl_proto_rawDescGZIP() []byte {
	file_tinyurl_proto_rawDescOnce.Do(func() {
		file_tinyurl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tinyurl_proto_rawDesc), len(file_tinyurl_proto_rawDesc)))
	})
	return file_tinyurl_proto_rawDescData
}

var file_tinyurl_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tinyurl_proto_goTypes = []any{
	(*TinyURLEncodeResObj)(nil), // 0: TinyURLEncodeResObj
	(*TinyURLEncodeReq)(nil),    // 1: TinyURLEncodeReq
	(*TinyURLEncodeResp)(nil),   // 2: TinyURLEncodeResp
	(*TinyURLDecodeResObj)(nil), // 3: TinyURLDecodeResObj
	(*TinyURLDecodeReq)(nil),    // 4: TinyURLDecodeReq
	(*TinyURLDecodeResp)(nil),   // 5: TinyURLDecodeResp
}
var file_tinyurl_proto_depIdxs = []int32{
	0, // 0: TinyURLEncodeResp.data:type_name -> TinyURLEncodeResObj
	3, // 1: TinyURLDecodeResp.data:type_name -> TinyURLDecodeResObj
	1, // 2: TinyURL.TinyURLEncode:input_type -> TinyURLEncodeReq
	4, // 3: TinyURL.TinyURLDecode:input_type -> TinyURLDecodeReq
	2, // 4: TinyURL.TinyURLEncode:output_type -> TinyURLEncodeResp
	5, // 5: TinyURL.TinyURLDecode:output_type -> TinyURLDecodeResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tinyurl_proto_init() }
func file_tinyurl_proto_init() {
	if File_tinyurl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tinyurl_proto_rawDesc), len(file_tinyurl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tinyurl_proto_goTypes,
		DependencyIndexes: file_tinyurl_proto_depIdxs,
		MessageInfos:      file_tinyurl_proto_msgTypes,
	}.Build()
	File_tinyurl_proto = out.File
	file_tinyurl_proto_goTypes = nil
	file_tinyurl_proto_depIdxs = nil
}
