// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: crypto.proto

package api_crypto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CryptoEncrypt
type CryptoEncryptResObj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptText   string                 `protobuf:"bytes,1,opt,name=encryptText,proto3" json:"encryptText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoEncryptResObj) Reset() {
	*x = CryptoEncryptResObj{}
	mi := &file_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoEncryptResObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoEncryptResObj) ProtoMessage() {}

func (x *CryptoEncryptResObj) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoEncryptResObj.ProtoReflect.Descriptor instead.
func (*CryptoEncryptResObj) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *CryptoEncryptResObj) GetEncryptText() string {
	if x != nil {
		return x.EncryptText
	}
	return ""
}

type CryptoEncryptReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	PlainText     string                 `protobuf:"bytes,2,opt,name=plainText,proto3" json:"plainText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoEncryptReq) Reset() {
	*x = CryptoEncryptReq{}
	mi := &file_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoEncryptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoEncryptReq) ProtoMessage() {}

func (x *CryptoEncryptReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoEncryptReq.ProtoReflect.Descriptor instead.
func (*CryptoEncryptReq) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *CryptoEncryptReq) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *CryptoEncryptReq) GetPlainText() string {
	if x != nil {
		return x.PlainText
	}
	return ""
}

type CryptoEncryptResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *CryptoEncryptResObj   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoEncryptResp) Reset() {
	*x = CryptoEncryptResp{}
	mi := &file_crypto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoEncryptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoEncryptResp) ProtoMessage() {}

func (x *CryptoEncryptResp) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoEncryptResp.ProtoReflect.Descriptor instead.
func (*CryptoEncryptResp) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{2}
}

func (x *CryptoEncryptResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CryptoEncryptResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CryptoEncryptResp) GetData() *CryptoEncryptResObj {
	if x != nil {
		return x.Data
	}
	return nil
}

// CryptoDecrypt
type CryptoDecryptResObj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlainText     string                 `protobuf:"bytes,1,opt,name=plainText,proto3" json:"plainText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoDecryptResObj) Reset() {
	*x = CryptoDecryptResObj{}
	mi := &file_crypto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoDecryptResObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoDecryptResObj) ProtoMessage() {}

func (x *CryptoDecryptResObj) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoDecryptResObj.ProtoReflect.Descriptor instead.
func (*CryptoDecryptResObj) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{3}
}

func (x *CryptoDecryptResObj) GetPlainText() string {
	if x != nil {
		return x.PlainText
	}
	return ""
}

type CryptoDecryptReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	EncryptText   string                 `protobuf:"bytes,2,opt,name=encryptText,proto3" json:"encryptText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoDecryptReq) Reset() {
	*x = CryptoDecryptReq{}
	mi := &file_crypto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoDecryptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoDecryptReq) ProtoMessage() {}

func (x *CryptoDecryptReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoDecryptReq.ProtoReflect.Descriptor instead.
func (*CryptoDecryptReq) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{4}
}

func (x *CryptoDecryptReq) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *CryptoDecryptReq) GetEncryptText() string {
	if x != nil {
		return x.EncryptText
	}
	return ""
}

type CryptoDecryptResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *CryptoDecryptResObj   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoDecryptResp) Reset() {
	*x = CryptoDecryptResp{}
	mi := &file_crypto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoDecryptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoDecryptResp) ProtoMessage() {}

func (x *CryptoDecryptResp) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoDecryptResp.ProtoReflect.Descriptor instead.
func (*CryptoDecryptResp) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{5}
}

func (x *CryptoDecryptResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CryptoDecryptResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CryptoDecryptResp) GetData() *CryptoDecryptResObj {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_crypto_proto protoreflect.FileDescriptor

const file_crypto_proto_rawDesc = "" +
	"\n" +
	"\fcrypto.proto\x1a\x1cgoogle/api/annotations.proto\"7\n" +
	"\x13CryptoEncryptResObj\x12 \n" +
	"\vencryptText\x18\x01 \x01(\tR\vencryptText\"N\n" +
	"\x10CryptoEncryptReq\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x1c\n" +
	"\tplainText\x18\x02 \x01(\tR\tplainText\"c\n" +
	"\x11CryptoEncryptResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.CryptoEncryptResObjR\x04data\"3\n" +
	"\x13CryptoDecryptResObj\x12\x1c\n" +
	"\tplainText\x18\x01 \x01(\tR\tplainText\"R\n" +
	"\x10CryptoDecryptReq\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12 \n" +
	"\vencryptText\x18\x02 \x01(\tR\vencryptText\"c\n" +
	"\x11CryptoDecryptResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.CryptoDecryptResObjR\x04data2\xb0\x01\n" +
	"\x06Crypto\x12R\n" +
	"\rCryptoEncrypt\x12\x11.CryptoEncryptReq\x1a\x12.CryptoEncryptResp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/crypto/encrypt\x12R\n" +
	"\rCryptoDecrypt\x12\x11.CryptoDecryptReq\x1a\x12.CryptoDecryptResp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/crypto/decryptB\x0eZ\f.;api_cryptob\x06proto3"

var (
	file_crypto_proto_rawDescOnce sync.Once
	file_crypto_proto_rawDescData []byte
)

func file_crypto_proto_rawDescGZIP() []byte {
	file_crypto_proto_rawDescOnce.Do(func() {
		file_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)))
	})
	return file_crypto_proto_rawDescData
}

var file_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_crypto_proto_goTypes = []any{
	(*CryptoEncryptResObj)(nil), // 0: CryptoEncryptResObj
	(*CryptoEncryptReq)(nil),    // 1: CryptoEncryptReq
	(*CryptoEncryptResp)(nil),   // 2: CryptoEncryptResp
	(*CryptoDecryptResObj)(nil), // 3: CryptoDecryptResObj
	(*CryptoDecryptReq)(nil),    // 4: CryptoDecryptReq
	(*CryptoDecryptResp)(nil),   // 5: CryptoDecryptResp
}
var file_crypto_proto_depIdxs = []int32{
	0, // 0: CryptoEncryptResp.data:type_name -> CryptoEncryptResObj
	3, // 1: CryptoDecryptResp.data:type_name -> CryptoDecryptResObj
	1, // 2: Crypto.CryptoEncrypt:input_type -> CryptoEncryptReq
	4, // 3: Crypto.CryptoDecrypt:input_type -> CryptoDecryptReq
	2, // 4: Crypto.CryptoEncrypt:output_type -> CryptoEncryptResp
	5, // 5: Crypto.CryptoDecrypt:output_type -> CryptoDecryptResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_crypto_proto_init() }
func file_crypto_proto_init() {
	if File_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crypto_proto_goTypes,
		DependencyIndexes: file_crypto_proto_depIdxs,
		MessageInfos:      file_crypto_proto_msgTypes,
	}.Build()
	File_crypto_proto = out.File
	file_crypto_proto_goTypes = nil
	file_crypto_proto_depIdxs = nil
}
