// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pastebin.proto

package api_pastebin

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PastebinSubmit
type PastebinSubmitResObj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purl          string                 `protobuf:"bytes,1,opt,name=purl,proto3" json:"purl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PastebinSubmitResObj) Reset() {
	*x = PastebinSubmitResObj{}
	mi := &file_pastebin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PastebinSubmitResObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PastebinSubmitResObj) ProtoMessage() {}

func (x *PastebinSubmitResObj) ProtoReflect() protoreflect.Message {
	mi := &file_pastebin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PastebinSubmitResObj.ProtoReflect.Descriptor instead.
func (*PastebinSubmitResObj) Descriptor() ([]byte, []int) {
	return file_pastebin_proto_rawDescGZIP(), []int{0}
}

func (x *PastebinSubmitResObj) GetPurl() string {
	if x != nil {
		return x.Purl
	}
	return ""
}

type PastebinSubmitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Syntax        string                 `protobuf:"bytes,2,opt,name=syntax,proto3" json:"syntax,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"` // Optional password for protecting the pastebin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PastebinSubmitReq) Reset() {
	*x = PastebinSubmitReq{}
	mi := &file_pastebin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PastebinSubmitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PastebinSubmitReq) ProtoMessage() {}

func (x *PastebinSubmitReq) ProtoReflect() protoreflect.Message {
	mi := &file_pastebin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PastebinSubmitReq.ProtoReflect.Descriptor instead.
func (*PastebinSubmitReq) Descriptor() ([]byte, []int) {
	return file_pastebin_proto_rawDescGZIP(), []int{1}
}

func (x *PastebinSubmitReq) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PastebinSubmitReq) GetSyntax() string {
	if x != nil {
		return x.Syntax
	}
	return ""
}

func (x *PastebinSubmitReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PastebinSubmitReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PastebinSubmitResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *PastebinSubmitResObj  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PastebinSubmitResp) Reset() {
	*x = PastebinSubmitResp{}
	mi := &file_pastebin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PastebinSubmitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PastebinSubmitResp) ProtoMessage() {}

func (x *PastebinSubmitResp) ProtoReflect() protoreflect.Message {
	mi := &file_pastebin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PastebinSubmitResp.ProtoReflect.Descriptor instead.
func (*PastebinSubmitResp) Descriptor() ([]byte, []int) {
	return file_pastebin_proto_rawDescGZIP(), []int{2}
}

func (x *PastebinSubmitResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PastebinSubmitResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PastebinSubmitResp) GetData() *PastebinSubmitResObj {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pastebin_proto protoreflect.FileDescriptor

const file_pastebin_proto_rawDesc = "" +
	"\n" +
	"\x0epastebin.proto\x1a\x1cgoogle/api/annotations.proto\"*\n" +
	"\x14PastebinSubmitResObj\x12\x12\n" +
	"\x04purl\x18\x01 \x01(\tR\x04purl\"s\n" +
	"\x11PastebinSubmitReq\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x16\n" +
	"\x06syntax\x18\x02 \x01(\tR\x06syntax\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"e\n" +
	"\x12PastebinSubmitResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.PastebinSubmitResObjR\x04data2b\n" +
	"\bPastebin\x12V\n" +
	"\x0ePastebinSubmit\x12\x12.PastebinSubmitReq\x1a\x13.PastebinSubmitResp\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/pastebin/submitB\x10Z\x0e.;api_pastebinb\x06proto3"

var (
	file_pastebin_proto_rawDescOnce sync.Once
	file_pastebin_proto_rawDescData []byte
)

func file_pastebin_proto_rawDescGZIP() []byte {
	file_pastebin_proto_rawDescOnce.Do(func() {
		file_pastebin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pastebin_proto_rawDesc), len(file_pastebin_proto_rawDesc)))
	})
	return file_pastebin_proto_rawDescData
}

var file_pastebin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pastebin_proto_goTypes = []any{
	(*PastebinSubmitResObj)(nil), // 0: PastebinSubmitResObj
	(*PastebinSubmitReq)(nil),    // 1: PastebinSubmitReq
	(*PastebinSubmitResp)(nil),   // 2: PastebinSubmitResp
}
var file_pastebin_proto_depIdxs = []int32{
	0, // 0: PastebinSubmitResp.data:type_name -> PastebinSubmitResObj
	1, // 1: Pastebin.PastebinSubmit:input_type -> PastebinSubmitReq
	2, // 2: Pastebin.PastebinSubmit:output_type -> PastebinSubmitResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pastebin_proto_init() }
func file_pastebin_proto_init() {
	if File_pastebin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pastebin_proto_rawDesc), len(file_pastebin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pastebin_proto_goTypes,
		DependencyIndexes: file_pastebin_proto_depIdxs,
		MessageInfos:      file_pastebin_proto_msgTypes,
	}.Build()
	File_pastebin_proto = out.File
	file_pastebin_proto_goTypes = nil
	file_pastebin_proto_depIdxs = nil
}
