// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: pastebin.proto

package api_pastebin

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// PastebinSubmit
type PastebinSubmitResObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Purl string `protobuf:"bytes,1,opt,name=purl,proto3" json:"purl,omitempty"`
}

func (x *PastebinSubmitResObj) Reset() {
	*x = PastebinSubmitResObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pastebin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PastebinSubmitResObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PastebinSubmitResObj) ProtoMessage() {}

func (x *PastebinSubmitResObj) ProtoReflect() protoreflect.Message {
	mi := &file_pastebin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PastebinSubmitResObj.ProtoReflect.Descriptor instead.
func (*PastebinSubmitResObj) Descriptor() ([]byte, []int) {
	return file_pastebin_proto_rawDescGZIP(), []int{0}
}

func (x *PastebinSubmitResObj) GetPurl() string {
	if x != nil {
		return x.Purl
	}
	return ""
}

type PastebinSubmitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Syntax string `protobuf:"bytes,2,opt,name=syntax,proto3" json:"syntax,omitempty"`
	Text   string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *PastebinSubmitReq) Reset() {
	*x = PastebinSubmitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pastebin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PastebinSubmitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PastebinSubmitReq) ProtoMessage() {}

func (x *PastebinSubmitReq) ProtoReflect() protoreflect.Message {
	mi := &file_pastebin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PastebinSubmitReq.ProtoReflect.Descriptor instead.
func (*PastebinSubmitReq) Descriptor() ([]byte, []int) {
	return file_pastebin_proto_rawDescGZIP(), []int{1}
}

func (x *PastebinSubmitReq) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PastebinSubmitReq) GetSyntax() string {
	if x != nil {
		return x.Syntax
	}
	return ""
}

func (x *PastebinSubmitReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PastebinSubmitResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string                `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *PastebinSubmitResObj `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PastebinSubmitResp) Reset() {
	*x = PastebinSubmitResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pastebin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PastebinSubmitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PastebinSubmitResp) ProtoMessage() {}

func (x *PastebinSubmitResp) ProtoReflect() protoreflect.Message {
	mi := &file_pastebin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PastebinSubmitResp.ProtoReflect.Descriptor instead.
func (*PastebinSubmitResp) Descriptor() ([]byte, []int) {
	return file_pastebin_proto_rawDescGZIP(), []int{2}
}

func (x *PastebinSubmitResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PastebinSubmitResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PastebinSubmitResp) GetData() *PastebinSubmitResObj {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pastebin_proto protoreflect.FileDescriptor

var file_pastebin_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x61, 0x73, 0x74, 0x65, 0x62, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a,
	0x0a, 0x14, 0x50, 0x61, 0x73, 0x74, 0x65, 0x62, 0x69, 0x6e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x75, 0x72, 0x6c, 0x22, 0x57, 0x0a, 0x11, 0x50, 0x61,
	0x73, 0x74, 0x65, 0x62, 0x69, 0x6e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6e, 0x74, 0x61,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x22, 0x65, 0x0a, 0x12, 0x50, 0x61, 0x73, 0x74, 0x65, 0x62, 0x69, 0x6e, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x50, 0x61, 0x73, 0x74, 0x65, 0x62, 0x69, 0x6e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x4f, 0x62, 0x6a, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x62, 0x0a, 0x08, 0x50, 0x61,
	0x73, 0x74, 0x65, 0x62, 0x69, 0x6e, 0x12, 0x56, 0x0a, 0x0e, 0x50, 0x61, 0x73, 0x74, 0x65, 0x62,
	0x69, 0x6e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x2e, 0x50, 0x61, 0x73, 0x74, 0x65,
	0x62, 0x69, 0x6e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x50,
	0x61, 0x73, 0x74, 0x65, 0x62, 0x69, 0x6e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x10, 0x2f, 0x70, 0x61, 0x73, 0x74,
	0x65, 0x62, 0x69, 0x6e, 0x2f, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x3a, 0x01, 0x2a, 0x42, 0x10,
	0x5a, 0x0e, 0x2e, 0x3b, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x61, 0x73, 0x74, 0x65, 0x62, 0x69, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pastebin_proto_rawDescOnce sync.Once
	file_pastebin_proto_rawDescData = file_pastebin_proto_rawDesc
)

func file_pastebin_proto_rawDescGZIP() []byte {
	file_pastebin_proto_rawDescOnce.Do(func() {
		file_pastebin_proto_rawDescData = protoimpl.X.CompressGZIP(file_pastebin_proto_rawDescData)
	})
	return file_pastebin_proto_rawDescData
}

var file_pastebin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pastebin_proto_goTypes = []interface{}{
	(*PastebinSubmitResObj)(nil), // 0: PastebinSubmitResObj
	(*PastebinSubmitReq)(nil),    // 1: PastebinSubmitReq
	(*PastebinSubmitResp)(nil),   // 2: PastebinSubmitResp
}
var file_pastebin_proto_depIdxs = []int32{
	0, // 0: PastebinSubmitResp.data:type_name -> PastebinSubmitResObj
	1, // 1: Pastebin.PastebinSubmit:input_type -> PastebinSubmitReq
	2, // 2: Pastebin.PastebinSubmit:output_type -> PastebinSubmitResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pastebin_proto_init() }
func file_pastebin_proto_init() {
	if File_pastebin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pastebin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PastebinSubmitResObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pastebin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PastebinSubmitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pastebin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PastebinSubmitResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pastebin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pastebin_proto_goTypes,
		DependencyIndexes: file_pastebin_proto_depIdxs,
		MessageInfos:      file_pastebin_proto_msgTypes,
	}.Build()
	File_pastebin_proto = out.File
	file_pastebin_proto_rawDesc = nil
	file_pastebin_proto_goTypes = nil
	file_pastebin_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PastebinClient is the client API for Pastebin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PastebinClient interface {
	PastebinSubmit(ctx context.Context, in *PastebinSubmitReq, opts ...grpc.CallOption) (*PastebinSubmitResp, error)
}

type pastebinClient struct {
	cc grpc.ClientConnInterface
}

func NewPastebinClient(cc grpc.ClientConnInterface) PastebinClient {
	return &pastebinClient{cc}
}

func (c *pastebinClient) PastebinSubmit(ctx context.Context, in *PastebinSubmitReq, opts ...grpc.CallOption) (*PastebinSubmitResp, error) {
	out := new(PastebinSubmitResp)
	err := c.cc.Invoke(ctx, "/Pastebin/PastebinSubmit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PastebinServer is the server API for Pastebin service.
type PastebinServer interface {
	PastebinSubmit(context.Context, *PastebinSubmitReq) (*PastebinSubmitResp, error)
}

// UnimplementedPastebinServer can be embedded to have forward compatible implementations.
type UnimplementedPastebinServer struct {
}

func (*UnimplementedPastebinServer) PastebinSubmit(context.Context, *PastebinSubmitReq) (*PastebinSubmitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PastebinSubmit not implemented")
}

func RegisterPastebinServer(s *grpc.Server, srv PastebinServer) {
	s.RegisterService(&_Pastebin_serviceDesc, srv)
}

func _Pastebin_PastebinSubmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PastebinSubmitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PastebinServer).PastebinSubmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pastebin/PastebinSubmit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PastebinServer).PastebinSubmit(ctx, req.(*PastebinSubmitReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pastebin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Pastebin",
	HandlerType: (*PastebinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PastebinSubmit",
			Handler:    _Pastebin_PastebinSubmit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pastebin.proto",
}
