version: '3.1'

services:
  server_dc:
    container_name: server_dc
    build: ../../
    # image: binacslee/binacs-cn:latest
    command: ./work/server start --configFile /docker-compose/config.toml
    volumes:
      - ./:/docker-compose
    ports:
      - 80:80
      - 443:443
      - 9500:9500
      - 9999:9999
    networks:
      - binacs_local

  mysql_dc:
    container_name: mysql_dc
    image: mysql
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: password
    networks:
      - binacs_local

  redis_dc:
    container_name: redis_dc
    image: redis
    command: --requirepass password
    ports:
      - 6379:6379
    networks:
      - binacs_local

  jaeger_dc:
    container_name: jaeger_dc
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
       - binacs_local
  
  cryptfunc_base64_dc:
    container_name: cryptfunc-base64-svc.cryptfunc
    image: binacslee/cryptfunc:latest
    command: fs --port=:8888 --algo=BASE64
    networks:
      - binacs_local

  cryptfunc_aes_dc:
    container_name: cryptfunc-aes-svc.cryptfunc
    image: binacslee/cryptfunc:latest
    command: fs --port=:8888 --algo=AES
    networks:
      - binacs_local

  cryptfunc_des_dc:
    container_name: cryptfunc-des-svc.cryptfunc
    image: binacslee/cryptfunc:latest
    command: fs --port=:8888 --algo=DES
    networks:
      - binacs_local

networks:
  binacs_local:
    name: binacs_local
    driver: bridge