/*
 * user.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BinacsApiUserV1UserInfoObj struct {
	Id    string   `json:"id,omitempty"`
	Role  string   `json:"role,omitempty"`
	Desc  string   `json:"desc,omitempty"`
	Ctime string   `json:"ctime,omitempty"`
	More  []string `json:"more,omitempty"`
}
