// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: cos.proto

package api_cos

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CosBucketURL
type CosBucketURLResObj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketURL     string                 `protobuf:"bytes,1,opt,name=bucketURL,proto3" json:"bucketURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CosBucketURLResObj) Reset() {
	*x = CosBucketURLResObj{}
	mi := &file_cos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosBucketURLResObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosBucketURLResObj) ProtoMessage() {}

func (x *CosBucketURLResObj) ProtoReflect() protoreflect.Message {
	mi := &file_cos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosBucketURLResObj.ProtoReflect.Descriptor instead.
func (*CosBucketURLResObj) Descriptor() ([]byte, []int) {
	return file_cos_proto_rawDescGZIP(), []int{0}
}

func (x *CosBucketURLResObj) GetBucketURL() string {
	if x != nil {
		return x.BucketURL
	}
	return ""
}

type CosBucketURLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CosBucketURLReq) Reset() {
	*x = CosBucketURLReq{}
	mi := &file_cos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosBucketURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosBucketURLReq) ProtoMessage() {}

func (x *CosBucketURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_cos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosBucketURLReq.ProtoReflect.Descriptor instead.
func (*CosBucketURLReq) Descriptor() ([]byte, []int) {
	return file_cos_proto_rawDescGZIP(), []int{1}
}

type CosBucketURLResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *CosBucketURLResObj    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CosBucketURLResp) Reset() {
	*x = CosBucketURLResp{}
	mi := &file_cos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosBucketURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosBucketURLResp) ProtoMessage() {}

func (x *CosBucketURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_cos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosBucketURLResp.ProtoReflect.Descriptor instead.
func (*CosBucketURLResp) Descriptor() ([]byte, []int) {
	return file_cos_proto_rawDescGZIP(), []int{2}
}

func (x *CosBucketURLResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CosBucketURLResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CosBucketURLResp) GetData() *CosBucketURLResObj {
	if x != nil {
		return x.Data
	}
	return nil
}

// CosPut
type CosPutResObj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CosURI        string                 `protobuf:"bytes,1,opt,name=cosURI,proto3" json:"cosURI,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CosPutResObj) Reset() {
	*x = CosPutResObj{}
	mi := &file_cos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosPutResObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosPutResObj) ProtoMessage() {}

func (x *CosPutResObj) ProtoReflect() protoreflect.Message {
	mi := &file_cos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosPutResObj.ProtoReflect.Descriptor instead.
func (*CosPutResObj) Descriptor() ([]byte, []int) {
	return file_cos_proto_rawDescGZIP(), []int{3}
}

func (x *CosPutResObj) GetCosURI() string {
	if x != nil {
		return x.CosURI
	}
	return ""
}

type CosPutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileBytes     []byte                 `protobuf:"bytes,2,opt,name=fileBytes,proto3" json:"fileBytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CosPutReq) Reset() {
	*x = CosPutReq{}
	mi := &file_cos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosPutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosPutReq) ProtoMessage() {}

func (x *CosPutReq) ProtoReflect() protoreflect.Message {
	mi := &file_cos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosPutReq.ProtoReflect.Descriptor instead.
func (*CosPutReq) Descriptor() ([]byte, []int) {
	return file_cos_proto_rawDescGZIP(), []int{4}
}

func (x *CosPutReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CosPutReq) GetFileBytes() []byte {
	if x != nil {
		return x.FileBytes
	}
	return nil
}

type CosPutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *CosPutResObj          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CosPutResp) Reset() {
	*x = CosPutResp{}
	mi := &file_cos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosPutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosPutResp) ProtoMessage() {}

func (x *CosPutResp) ProtoReflect() protoreflect.Message {
	mi := &file_cos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosPutResp.ProtoReflect.Descriptor instead.
func (*CosPutResp) Descriptor() ([]byte, []int) {
	return file_cos_proto_rawDescGZIP(), []int{5}
}

func (x *CosPutResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CosPutResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CosPutResp) GetData() *CosPutResObj {
	if x != nil {
		return x.Data
	}
	return nil
}

// CosGet
type CosGetResObj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileBytes     []byte                 `protobuf:"bytes,1,opt,name=fileBytes,proto3" json:"fileBytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CosGetResObj) Reset() {
	*x = CosGetResObj{}
	mi := &file_cos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosGetResObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosGetResObj) ProtoMessage() {}

func (x *CosGetResObj) ProtoReflect() protoreflect.Message {
	mi := &file_cos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosGetResObj.ProtoReflect.Descriptor instead.
func (*CosGetResObj) Descriptor() ([]byte, []int) {
	return file_cos_proto_rawDescGZIP(), []int{6}
}

func (x *CosGetResObj) GetFileBytes() []byte {
	if x != nil {
		return x.FileBytes
	}
	return nil
}

type CosGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CosURI        string                 `protobuf:"bytes,1,opt,name=cosURI,proto3" json:"cosURI,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CosGetReq) Reset() {
	*x = CosGetReq{}
	mi := &file_cos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosGetReq) ProtoMessage() {}

func (x *CosGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosGetReq.ProtoReflect.Descriptor instead.
func (*CosGetReq) Descriptor() ([]byte, []int) {
	return file_cos_proto_rawDescGZIP(), []int{7}
}

func (x *CosGetReq) GetCosURI() string {
	if x != nil {
		return x.CosURI
	}
	return ""
}

type CosGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *CosGetResObj          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CosGetResp) Reset() {
	*x = CosGetResp{}
	mi := &file_cos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosGetResp) ProtoMessage() {}

func (x *CosGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_cos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosGetResp.ProtoReflect.Descriptor instead.
func (*CosGetResp) Descriptor() ([]byte, []int) {
	return file_cos_proto_rawDescGZIP(), []int{8}
}

func (x *CosGetResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CosGetResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CosGetResp) GetData() *CosGetResObj {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_cos_proto protoreflect.FileDescriptor

const file_cos_proto_rawDesc = "" +
	"\n" +
	"\tcos.proto\x1a\x1cgoogle/api/annotations.proto\"2\n" +
	"\x12CosBucketURLResObj\x12\x1c\n" +
	"\tbucketURL\x18\x01 \x01(\tR\tbucketURL\"\x11\n" +
	"\x0fCosBucketURLReq\"a\n" +
	"\x10CosBucketURLResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12'\n" +
	"\x04data\x18\x03 \x01(\v2\x13.CosBucketURLResObjR\x04data\"&\n" +
	"\fCosPutResObj\x12\x16\n" +
	"\x06cosURI\x18\x01 \x01(\tR\x06cosURI\"E\n" +
	"\tCosPutReq\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x1c\n" +
	"\tfileBytes\x18\x02 \x01(\fR\tfileBytes\"U\n" +
	"\n" +
	"CosPutResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.CosPutResObjR\x04data\",\n" +
	"\fCosGetResObj\x12\x1c\n" +
	"\tfileBytes\x18\x01 \x01(\fR\tfileBytes\"#\n" +
	"\tCosGetReq\x12\x16\n" +
	"\x06cosURI\x18\x01 \x01(\tR\x06cosURI\"U\n" +
	"\n" +
	"CosGetResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.CosGetResObjR\x04data2\xc5\x01\n" +
	"\x03Cos\x12N\n" +
	"\fCosBucketURL\x12\x10.CosBucketURLReq\x1a\x11.CosBucketURLResp\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/cos/bucketurl\x126\n" +
	"\x06CosPut\x12\n" +
	".CosPutReq\x1a\v.CosPutResp\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/cos/put\x126\n" +
	"\x06CosGet\x12\n" +
	".CosGetReq\x1a\v.CosGetResp\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/cos/getB\vZ\t.;api_cosb\x06proto3"

var (
	file_cos_proto_rawDescOnce sync.Once
	file_cos_proto_rawDescData []byte
)

func file_cos_proto_rawDescGZIP() []byte {
	file_cos_proto_rawDescOnce.Do(func() {
		file_cos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cos_proto_rawDesc), len(file_cos_proto_rawDesc)))
	})
	return file_cos_proto_rawDescData
}

var file_cos_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cos_proto_goTypes = []any{
	(*CosBucketURLResObj)(nil), // 0: CosBucketURLResObj
	(*CosBucketURLReq)(nil),    // 1: CosBucketURLReq
	(*CosBucketURLResp)(nil),   // 2: CosBucketURLResp
	(*CosPutResObj)(nil),       // 3: CosPutResObj
	(*CosPutReq)(nil),          // 4: CosPutReq
	(*CosPutResp)(nil),         // 5: CosPutResp
	(*CosGetResObj)(nil),       // 6: CosGetResObj
	(*CosGetReq)(nil),          // 7: CosGetReq
	(*CosGetResp)(nil),         // 8: CosGetResp
}
var file_cos_proto_depIdxs = []int32{
	0, // 0: CosBucketURLResp.data:type_name -> CosBucketURLResObj
	3, // 1: CosPutResp.data:type_name -> CosPutResObj
	6, // 2: CosGetResp.data:type_name -> CosGetResObj
	1, // 3: Cos.CosBucketURL:input_type -> CosBucketURLReq
	4, // 4: Cos.CosPut:input_type -> CosPutReq
	7, // 5: Cos.CosGet:input_type -> CosGetReq
	2, // 6: Cos.CosBucketURL:output_type -> CosBucketURLResp
	5, // 7: Cos.CosPut:output_type -> CosPutResp
	8, // 8: Cos.CosGet:output_type -> CosGetResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cos_proto_init() }
func file_cos_proto_init() {
	if File_cos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cos_proto_rawDesc), len(file_cos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cos_proto_goTypes,
		DependencyIndexes: file_cos_proto_depIdxs,
		MessageInfos:      file_cos_proto_msgTypes,
	}.Build()
	File_cos_proto = out.File
	file_cos_proto_goTypes = nil
	file_cos_proto_depIdxs = nil
}
