apiVersion: apps/v1
kind: Deployment
metadata:
  name: binacs-cn
  namespace: binacs-cn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binacs-cn
  template:
    metadata:
      labels:
        app: binacs-cn
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        labelName: master
      containers:
      - name: server
        image: binacslee/binacs-cn:latest
        command: ["/bin/sh","-c","/work/server start --configFile /kubernetes/config.toml"]
        ports:
          - name: http
            # binacs: 80 => 9080
            containerPort: 80
            protocol: TCP
          - name: https
            # binacs: 443 => 9443
            containerPort: 443
            protocol: TCP
          - name: grpc
            containerPort: 9500
            protocol: TCP
          # - name: perf
          #   containerPort: 9999
          #   protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /kubernetes
            readOnly: true
          - name: tls
            mountPath: /tls
            readOnly: true
      - name: redis
        image: redis:latest
        command: ["redis-server", "--requirepass", "password"]
        ports:
          - name: rds
            containerPort: 6379
            protocol: TCP
      - name: mysql
        image: mysql:latest
        args:
          - '--default-authentication-plugin=mysql_native_password'
          - '--character-set-server=utf8mb4'
          - '--collation-server=utf8mb4_unicode_ci'
          - '--user=root'
        env:
          - name: MYSQL_DATABASE
            value: testdb
          - name: MYSQL_ROOT_PASSWORD
            value: password
        ports:
          - name: mysql
            containerPort: 3306
            protocol: TCP
        volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
      volumes:
        - name: tls
          secret:
            secretName: tls-api
        - name: config
          hostPath:
            path: /home/web/config
        - name: mysql
          hostPath:
            path: /home/web/mysqldata

---
apiVersion: v1
kind: Service
metadata:
  name: binacs-cn-service
  namespace: binacs-cn
spec:
  type: ClusterIP
  selector:
    app: binacs-cn
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: grpc
    port: 9500
    targetPort: 9500
  # - name: perf
  #   port: 9999
  #   targetPort: 9999