
workspace = "/work/"
file = "/kubernetes/config.toml"
mode = "all"

[GRPCConfig]
HttpPort = "9500"
CertPath = "/tls/tls.crt"  # kubernetes secret keys
KeyPath  = "/tls/tls.key"
Host     = "api.binacs-cn"            # for test
[WebConfig]
HttpPort    = "80"
HttpsPort   = "443"
SSLRedirect = false
TmplPath    = "/work/template/"
CertPath    = "/tls/binacs.cn.crt"
KeyPath     = "/tls/binacs.cn.key"
Host        = "binacs.cn"             # for test
[WebConfig.K8sService]
"CryptoBASE64" = "cryptfunc-base64-svc.cryptfunc.svc.cluster.local:8888"
"CryptoAES"    = "cryptfunc-aes-svc.cryptfunc.svc.cluster.local:8888"
"CryptoDES"    = "cryptfunc-des-svc.cryptfunc.svc.cluster.local:8888"

[LogConfig]
File  = "/work/server.log"
Level = "debug"

[TraceConfig]
"ServiceName"   = "binacs-cn"
"AgentHostPort" = "jaeger-agent.binacs-cn.svc.cluster.local:6831"

[RedisConfig]
Network      = "tcp"
Addr         = "127.0.0.1:6379"
Password     = "password"
DB           = 0
PoolSize     = 10
MinIdleConns = 3

[MysqlConfig]
MaxIdleConns = 33
MaxOpenConns = 100
[[MysqlConfig.Conns]]
User     = "root"
Password = "password"
Host     = "mysql"
Port     = "3306"
DB       = "testdb"
