# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.2.2
        with:
          # Path to the Dockerfile
          file: ./Dockerfile
          # List of tags
          tags: binacslee/binacs-space:latest
          # Do not use cache when building the image
          no-cache: true
          # List of target platforms for build
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          # Push is a shorthand for --output=type=registry
          push: true
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
