name: Go

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Get dependencies
      run: go mod download

    - name: Run linter
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m

    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Build
      run: make

    - name: Build for multiple platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o bin/server-linux-amd64 ./cmd
        GOOS=darwin GOARCH=amd64 go build -o bin/server-darwin-amd64 ./cmd
        GOOS=windows GOARCH=amd64 go build -o bin/server-windows-amd64.exe ./cmd

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: server-binaries
        path: bin/

